apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-rolebinding
  namespace: project   # ✅ match your deployment's namespace
subjects:
  - kind: ServiceAccount
    name: nginx-sa           # ✅ match the SA used in the deployment
    namespace: project
roleRef:
  kind: Role
  name: nginx-role
  apiGroup: rbac.authorization.k8s.io
